### ISSUE TITLE
Breaks package_create API requests

### ISSUE THREAD

**Issue by rodowi** [openspending/ckanext-budgets#8]
When trying to upsert resources through the API I get validation errors:

```
create_dataset:  {u'__type': u'Validation Error', u'resources': [{u'year': [u'Falta el valor']}, {u'year': [u'Falta el valor']}, {u'year': [u'Falta el valor']}, {u'year': [u'Falta el valor']}, {u'year': [u'Falta el valor']}]}
Something went wrong
```

looks like the field "year" is enforced,

IMHO, this should be optional when not creating BDP datasets

**Comment by trickvi** [comment]
Closed via b5329175d48da5e379a3cb4f1db8599b3b833647
